### ISSUE TITLE
Replace all references of Frog by Darwin

### ISSUE THREAD

**Issue by pmatos** [pmatos/darwin#3]
To complete the fork, it would be great to have all references in code and docs changed from `frog` to `darwin`.

**Comment by JorgeAndd** [comment]
I'd like to give it a try.
Do I just need to change references to the word `frog` to be `darwin`?

**Comment by pmatos** [comment]
Yes. That should be mostly it. Although in code, some careful might have to be exercised. Happy to look at a draft PR once you have something and work it out together with you.

**Comment by pmatos** [comment]
@JorgeAndd feel free to start for example with a PR just for the documentation and then go for the code. I am happy if you want to split the contributions into several PRs.
