### ISSUE TITLE
Coexistence with frog?

### ISSUE THREAD

**Issue by srfoster** [pmatos/darwin#5]
For those of us migrating from frog, it might be nice to be able to install darwin without having to remove frog.

I get:

```
raco pkg install: packages conflict
  package: darwin
  package: frog
  module path: (lib "example/_src/A-Non-Post-Scribble-Page.scrbl")
```

**Comment by pmatos** [comment]
@srfoster Thanks for pointing this out to me. I will get this fixed.

**Comment by pmatos** [comment]
This should be fixed now.
